name: Test Cleanup
description: Uploads Test Logs and prints system info to the console after test runs.
inputs:
  artifact-prefix:
    description: >
      Prefix for the uploaded artifact name. Full artifact name will be {prefix}-logs.
      This is used to differentiate logs from different test runs (e.g. system vs non-system tests).
    required: true

runs:
  using: composite
  steps:
  - name: Upload logs
    if: ${{ always() }}
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.artifact-prefix }}-logs
      path: log

  - name: Capture System Info
    if: ${{ always() }}
    shell: bash
    run: |
      echo "*****"
      echo "System Info"
      uname -a
      echo "-----"
      env | sort
      echo "*****"
