name: Project Stats
description: Runs `bin/rails stats` and converts the output to a Markdown Table for the GitHub Actions summary.
inputs:
  install-ruby:
    description: >
      Whether Ruby & Gems install should be performed before running the command.
      Set this to false if you're using this action as a step within a larger job that has already setup Ruby.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Install Ruby and Gems
      uses: ruby/setup-ruby@v1
      if: inputs.install-ruby == 'true'
      with:
        bundler-cache: true

    - name: Run Stats Command and Capture Output
      id: run-stats
      shell: bash
      run: |
        table="$(bin/rails stats | ${{ github.action_path }}/scripts/format-stats)"
        echo "$table" >> "$GITHUB_STEP_SUMMARY"
        {
          echo "table<<PROJECT_STATS_EOF"
          echo "$table"
          echo "PROJECT_STATS_EOF"
        } >> "$GITHUB_OUTPUT"

outputs:
  table:
    description: The Markdown table of `bin/rails stats` output
    value: ${{ steps.run-stats.outputs.table }}
