name: 'Compile Assets'
description: 'Compiles Rails assets if not cached'

inputs:
  asset_cache_key_files:
    description: 'Files for Rails assets cache key'
    type: string
    required: false
    default: 'app/assets/images/**/* app/assets/stylesheets/**/* app/javascript/**/* yarn.lock Gemfile.lock'

outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.check-asset-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Check if assets are already compiled
      id: check-asset-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          public/assets
          app/assets/builds
        key: rails-assets-${{ hashFiles(inputs.asset_cache_key_files) }}
        lookup-only: true

    - name: Enable corepack
      if: steps.check-asset-cache.outputs.cache-hit != 'true'
      run: corepack enable

    - name: Set up node
      if: steps.check-asset-cache.outputs.cache-hit != 'true'
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: yarn

    - name: Install Ruby and gems
      if: steps.check-asset-cache.outputs.cache-hit != 'true'
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Build assets
      if: steps.check-asset-cache.outputs.cache-hit != 'true'
      run: |
        yarn install --immutable
        yarn build

    - name: Cache Rails Precompiled Assets
      if: steps.check-asset-cache.outputs.cache-hit != 'true'
      id: lookup-cached-assets
      uses: actions/cache/save@v4
      with:
        path: |
          public/assets
          app/assets/builds
        key: rails-assets-${{ hashFiles(inputs.asset_cache_key_files) }}
