name: Compile Assets
description: Compiles Rails assets if not cached

outputs:
  cache-hit:
    description: Whether the cache was hit
    value: ${{ steps.check-asset-cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Check for Existing Precompiled Assets
      id: check-asset-cache
      uses: actions/cache/restore@v5
      with:
        path: |
          public/assets
          app/assets/builds
        key: rails-assets-${{ hashFiles('app/assets/images/**/*', 'app/assets/stylesheets/**/*', 'app/javascript/**/*', 'yarn.lock', 'Gemfile.lock') }}
        lookup-only: true

    - name: Enable Corepack
      if: ${{ steps.check-asset-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: corepack enable

    - name: Setup Node
      if: ${{ steps.check-asset-cache.outputs.cache-hit != 'true' }}
      uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: yarn

    - name: Install Ruby and Gems
      if: ${{ steps.check-asset-cache.outputs.cache-hit != 'true' }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Build Assets
      if: ${{ steps.check-asset-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        yarn install --immutable
        bundle exec rails assets:precompile

    - name: Cache Rails Precompiled Assets
      if: ${{ steps.check-asset-cache.outputs.cache-hit != 'true' }}
      id: lookup-cached-assets
      uses: actions/cache/save@v5
      with:
        path: |
          public/assets
          app/assets/builds
        key: rails-assets-${{ hashFiles('app/assets/images/**/*', 'app/assets/stylesheets/**/*', 'app/javascript/**/*', 'yarn.lock', 'Gemfile.lock') }}
